### ISSUE TITLE
The term catalog is american english and rough.

### ISSUE THREAD

**Issue by almereyda** [libresh/catalog#5]
This repository is called catalog, which is the american english (AE), global dominant and hegemonic form of the english language used and adopted more than often.

Since we try to establish small and independent cooperations, it could be favourable to use the more nuanced british english (BE) forms in our communication, since they read nicer and have a finer tone.

Additionally we are already working in a secondary or ternary language here, and may want to remind ourselves to the existence of alternative ways of doing and describing things, other than mainstream flattened AE, which is a poorer reification of BE.

Therefore I propose to rename this project to *catalogue*.

**Comment by pierreozoux** [comment]
done :)
